### ISSUE TITLE
Page 45 indent 

### ISSUE THREAD

**Issue by coop101** [PacktPublishing/Python-Scripting-in-Blender#2]
shouldn't ob.select_set(False) be indented?

**Comment by pKrime** [comment]
Hi, that's correct and I have reported the Erratum. I have added code for chapter 2 where the correct snippet is used

https://github.com/PacktPublishing/Python-Scripting-in-Blender/blob/main/ch2/0500_understanding_user_context.py#L55

thanks,
p.
