### ISSUE TITLE
ani_loop.blend file

### ISSUE THREAD

**Issue by emkademy** [PacktPublishing/Python-Scripting-in-Blender#9]
Hello,

I couldn't find the `ani_loop.blend` file mentioned at the beginning of Chapter 8. Could you direct me to the location of this file?

**Comment by pKrime** [comment]
Hi, thanks a lot for reporting this: the file was probably filtered out due to its size. I have shrinked it down and uploaded at

https://github.com/PacktPublishing/Python-Scripting-in-Blender/tree/main/ch8/_scenes_

cheers,
p.
